# Generated by Django 4.2.22 on 2025-08-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_salutation_name_20250707_1420'),
        ('press', '0036_remove_press_password_reset_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_hero_image', to='core.file', verbose_name='Press Hero'),
        ),
    ]
