# Generated by Django 4.2.22 on 2025-09-17 13:06

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0037_press_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='homepage_h1_text',
            field=models.CharField(blank=True, help_text='The H1 to display on the press homepage hero. Default is the press name if blank.', max_length=30, verbose_name='Homepage H1 Text'),
        ),
        migrations.AddField(
            model_name='press',
            name='homepage_slogan',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='A slogan to show in the Janeway hero. Optional.', verbose_name='Homepage Slogan'),
        ),
    ]
