# Generated by Django 4.2.22 on 2025-09-11 18:28

import core.file_system
from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='The hero to display on Press pages', null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=journal.models.cover_images_upload_path),
        ),
    ]
